spring:
  application:
    name: azurestorageclient
  cloud:
    config:
      failFast: false
      uri: http://cloudconfig:8888 

server:
  port: ${PORT:8001}

feign:
  hystrix:
    enabled: false    
    
azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=filespace22;AccountKey=xc/wS2bYdHpXf1nWwlt4yff3LtkXYK+Z23OaKUrCXsGJ4CbLjZVk2u32HD6ipV4oHT1RjlaA7oUkmKm98Bfngw==;EndpointSuffix=core.windows.net
    allow-telemetry: false
    